### ISSUE TITLE
Add support for connecting to devices

### ISSUE THREAD

**Issue by axelkar** [soxfox42/adbqr#1]
I have some code here that I wrote a couple of months ago, willing to license as MIT: https://git.axka.fi/adb-mdns-connect.git/tree/src/main.rs

**Comment by soxfox42** [comment]
I don't think I'll be able to use the code directly, sadly, since we used different mdns libraries, and I don't want to use two separate ones. Definitely a great suggestion though, I'll give it a go when I get some time.

**Comment by soxfox42** [comment]
This should now work, but I want to implement the other pairing method ("Pair device with pairing code") before I release 1.2.0.
